name: Build Pi Stream App for Upsilon

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-arm-none-eabi make git

    - name: Clone and build Upsilon-External API
      run: |
        echo "📥 Cloning Upsilon-External..."
        git clone https://github.com/UpsilonNumworks/Upsilon-External.git upsilon-external
        echo "🧱 Building API library..."
        make -C upsilon-external/api clean
        make -C upsilon-external/api
        echo "✅ Built files:" && ls -la upsilon-external/api

    - name: Build Pi Stream app (link with API)
      run: |
        echo "🔧 Building Pi Stream app for Upsilon..."
        make clean
        make API=./upsilon-external/api
        echo "✅ Build completed!" && ls -la app.elf && file app.elf

    - name: Create app package (TAR)
      run: |
        echo "📦 Creating TAR package..."
        tar -cf pi_stream_upsilon_app.tar app.elf app.icon icon.png
        ls -la pi_stream_upsilon_app.tar

    - name: Upload app package
      uses: actions/upload-artifact@v4
      with:
        name: pi-stream-upsilon-app
        path: |
          pi_stream_upsilon_app.tar
          app.elf
        if-no-files-found: error
