name: Build Pi Stream App for Upsilon

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential gcc-arm-none-eabi
    
    - name: Clone Upsilon-External for API
      run: |
        echo "📥 Cloning Upsilon-External repository for API..."
        git clone https://github.com/UpsilonNumworks/Upsilon-External.git upsilon-external
        
        echo "📂 Setting up API directory..."
        mkdir -p api
        cp -r upsilon-external/api/* api/
        
        echo "✅ API files available:"
        ls -la api/
    
    - name: Build Pi Stream app
      run: |
        echo "🔧 Building Pi Stream app for Upsilon..."
        
        # Update Makefile to use correct API path
        sed -i 's|API=../../api|API=./api|g' Makefile
        
        make clean
        make
        
        echo "✅ Build completed!"
        ls -la app.elf
        file app.elf
    
    - name: Create app package
      run: |
        echo "📦 Creating app package..."
        mkdir -p package
        cp app.elf package/
        cp icon.png package/
        cp app.icon package/
        
        # Create a simple TAR archive as required by Upsilon
        cd package
        tar -cf ../pi_stream_upsilon_app.tar *
        cd ..
        
        echo "✅ Package created!"
        ls -la *.tar
    
    - name: Upload app package
      uses: actions/upload-artifact@v4
      with:
        name: pi-stream-upsilon-app
        path: |
          pi_stream_upsilon_app.tar
          app.elf
        if-no-files-found: error